# Generated by Django 2.0.5 on 2018-06-15 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_user_profiling', '0001_initial'),
        ('onboarding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dpyinstituteuserclass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dpyinstituteclass',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='class_user_profiling.DpyDepartment'),
        ),
        migrations.AddField(
            model_name='dpyinstituteclass',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onboarding.DpyInstitute'),
        ),
    ]
