# Generated by Django 2.0.5 on 2018-06-22 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_user_profiling', '0003_auto_20180622_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpyInstituteClassSessionSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dpy_class_session_subject',
                'verbose_name': 'Class Session Subject',
            },
        ),
        migrations.AlterModelTable(
            name='dpyinstituteclasssession',
            table='dpy_class_session',
        ),
        migrations.AddField(
            model_name='dpyinstituteclasssessionsubjects',
            name='cs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='class_user_profiling.DpyInstituteClassSession'),
        ),
    ]
