# Generated by Django 2.0 on 2018-07-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_user_profiling', '0003_dpyinstituteclasssessionsubjectuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpyinstituteclasssessionsubjectuser',
            name='status',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='dpyinstituteclasssessionsubjectuser',
            name='type',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
