# Generated by Django 2.0.5 on 2018-07-20 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0002_auto_20180718_0656'),
        ('class_user_profiling', '0005_auto_20180717_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpyUserDayPresenties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_by', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default=0)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onboarding.DpyInstitute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Day Presenties',
                'db_table': 'dpy_institute_user_day_presenties',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dpyuserdaypresenties',
            unique_together={('user', 'institute', 'date')},
        ),
    ]
