# Generated by Django 2.0.5 on 2018-07-26 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_auto_20180718_0656'),
        ('class_user_profiling', '0006_auto_20180720_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpyClassBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default=0)),
                ('ic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='class_user_profiling.DpyInstituteClass')),
            ],
            options={
                'db_table': 'dpy_institute_class_batch',
                'verbose_name': 'Class Batch',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dpydepartment',
            unique_together={('institute', 'name')},
        ),
        migrations.AddField(
            model_name='dpyinstitutetimetable',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='class_user_profiling.DpyClassBatch'),
        ),
        migrations.AddField(
            model_name='dpyinstituteuserclass',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='class_user_profiling.DpyClassBatch'),
        ),
        migrations.AlterUniqueTogether(
            name='dpyclassbatch',
            unique_together={('ic', 'name')},
        ),
    ]
