# Generated by Django 2.0.5 on 2018-07-27 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_user_profiling', '0007_auto_20180726_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpyinstituteclass',
            name='batch',
        ),
        migrations.AlterField(
            model_name='dpyclassbatch',
            name='ic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch', to='class_user_profiling.DpyInstituteClass'),
        ),
        migrations.AlterField(
            model_name='dpyinstituteuserclass',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_batch', to='class_user_profiling.DpyClassBatch'),
        ),
    ]
