# Generated by Django 2.0 on 2018-07-15 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission_management', '0001_initial'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpyinstituteadmissionprospect',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onboarding.DpyInstitute'),
        ),
    ]
