# Generated by Django 2.0 on 2018-07-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_management', '0002_auto_20180719_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpyinstituteadmissionsusers',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
