# Generated by Django 2.0 on 2018-07-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpystudents',
            options={'managed': False},
        ),
    ]
