# Generated by Django 2.0 on 2018-06-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_dpystudents_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpystudents',
            options={'verbose_name': 'Students'},
        ),
    ]
