# Generated by Django 2.0 on 2018-06-20 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_dpystudents_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpystudents',
            name='user_id',
        ),
    ]
