# Generated by Django 2.0 on 2018-06-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='First Name', max_length=20)),
                ('middle_name', models.CharField(db_column='Middle Name', max_length=20)),
                ('last_name', models.CharField(db_column='Last Name', max_length=20)),
                ('designation', models.CharField(db_column='Designation', max_length=20)),
                ('department', models.CharField(db_column='Department', max_length=20)),
                ('gender', models.CharField(db_column='Gender', max_length=10)),
                ('date_of_join', models.CharField(db_column='Date of Join', max_length=10)),
                ('basic_salary', models.IntegerField(db_column='Basic Salary')),
                ('mobile_number', models.CharField(db_column='Mobile Number', max_length=12)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('casual_leaves', models.CharField(max_length=50)),
                ('paid_leaves', models.CharField(max_length=50)),
                ('sick_leaves', models.CharField(max_length=50)),
            ],
            options={
                'managed': False,
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=25)),
                ('leave_type', models.CharField(max_length=25)),
                ('start_date', models.CharField(max_length=25)),
                ('end_date', models.CharField(max_length=25)),
                ('reason', models.CharField(max_length=200)),
            ],
            options={
                'managed': False,
                'db_table': 'leave',
            },
        ),
    ]
