# Generated by Django 2.0 on 2018-06-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='dpy_employee',
        ),
        migrations.AlterModelTable(
            name='leave',
            table='dpy_employee_leave',
        ),
    ]
