# Generated by Django 2.0.5 on 2018-05-30 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpyInstituteUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('type', models.PositiveSmallIntegerField()),
                ('designation', models.CharField(max_length=100)),
                ('date_of_joining', models.DateTimeField()),
                ('date_of_leaving', models.DateTimeField(null=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default=0)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onboarding.DpyInstitute')),
            ],
            options={
                'db_table': 'dpy_institute_user',
            },
        ),
        migrations.AlterModelTable(
            name='dpyusers',
            table='dpy_user',
        ),
        migrations.AddField(
            model_name='dpyinstituteusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
