# Generated by Django 2.0 on 2018-07-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_auto_20180718_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpyUpdateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('table_id', models.IntegerField()),
                ('desc', models.TextField()),
                ('added_by', models.IntegerField(default=0)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dpy Update Log',
                'db_table': 'dpy_update_log',
                'managed': True,
            },
        ),
    ]
