# Generated by Django 2.0.5 on 2018-05-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_auto_20180530_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpyusers',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
