# Generated by Django 2.0 on 2018-06-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_dpyusers_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpyusers',
            name='user_id',
        ),
    ]
