# Generated by Django 2.0 on 2018-06-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_remove_dpyusers_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpyusers',
            name='password',
            field=models.CharField(default=123, max_length=100),
        ),
    ]
