# Generated by Django 2.0.5 on 2018-05-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_auto_20180530_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpyusers',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
