# Generated by Django 2.0.5 on 2018-05-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_auto_20180530_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpyusers',
            name='created_by',
            field=models.IntegerField(default=0),
        ),
    ]
