# Generated by Django 2.0.5 on 2018-06-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0010_auto_20180606_0540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpyinstitute',
            options={'verbose_name': 'Institute'},
        ),
        migrations.AlterModelOptions(
            name='dpyinstituteusers',
            options={'verbose_name': 'Institute User'},
        ),
        migrations.AlterModelOptions(
            name='dpyusers',
            options={'verbose_name': 'User'},
        ),
    ]
