# Generated by Django 2.0 on 2018-06-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpystudentsabsenties',
            options={'managed': True},
        ),
    ]
