# Generated by Django 2.0 on 2018-06-29 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_auto_20180628_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpystudentsabsenties',
            options={'managed': False},
        ),
    ]
