# Generated by Django 2.0 on 2018-07-02 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fees_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpyUserFeeIgnore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_discount', models.FloatField()),
                ('status', models.PositiveSmallIntegerField()),
                ('added_by', models.IntegerField(default=0)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(default=0)),
                ('updated_on', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dpyfeetype',
            options={'verbose_name': 'dpy_fee_type'},
        ),
        migrations.AlterModelOptions(
            name='dpyinstituteclassfee',
            options={'verbose_name': 'Institute Class Fee'},
        ),
        migrations.AddField(
            model_name='dpyuserfeeignore',
            name='institute_class_fee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fees_management.DpyInstituteClassFee'),
        ),
        migrations.AddField(
            model_name='dpyuserfeeignore',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
