# Generated by Django 2.0 on 2018-07-02 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
        ('fees_management', '0002_auto_20180702_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpyPaymentReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_or_chequeno', models.TextField(default=0, null=True)),
                ('response', models.TextField(default=0, null=True)),
                ('mop', models.IntegerField(default=4)),
                ('receipt_amount', models.FloatField()),
                ('status', models.PositiveSmallIntegerField()),
                ('added_by', models.IntegerField(default=0)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(default=0)),
                ('updated_on', models.IntegerField(default=0)),
                ('institute_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onboarding.DpyInstitute')),
            ],
            options={
                'db_table': 'dpy_payment_receipt',
                'verbose_name': 'Dpy Payment Receipt',
            },
        ),
        migrations.AlterModelOptions(
            name='dpyuserfeeignore',
            options={'verbose_name': 'Dpy User Fee Ignore'},
        ),
        migrations.AlterModelTable(
            name='dpyuserfeeignore',
            table='dpy_user_fee_ignore',
        ),
    ]
