# Generated by Django 2.0 on 2018-07-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_user_profiling', '0006_auto_20180720_1218'),
        ('fees_management', '0002_auto_20180725_0707'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dpyinstituteclassfee',
            unique_together={('institute_class', 'display_name')},
        ),
    ]
