# Generated by Django 2.0 on 2018-07-28 11:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fees_management', '0003_auto_20180725_0943'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dpyuserfeeignore',
            unique_together={('institute_class_fee', 'user')},
        ),
    ]
