# Generated by Django 2.0 on 2018-07-02 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fees_management', '0003_auto_20180702_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpyFeeTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.FloatField()),
                ('cycle', models.IntegerField()),
                ('cycle_slot', models.IntegerField()),
                ('dsc', models.TextField()),
                ('mop', models.IntegerField(default=1)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('added_by', models.IntegerField(default=0)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(default=0)),
                ('updated_on', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dpy_fee_transaction',
                'verbose_name': 'Dpy Payment Receipt',
            },
        ),
        migrations.AlterField(
            model_name='dpyinstituteclassfee',
            name='bifercations',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='dpyfeetransaction',
            name='institute_class_fee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fees_management.DpyInstituteClassFee'),
        ),
        migrations.AddField(
            model_name='dpyfeetransaction',
            name='receipt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fees_management.DpyPaymentReceipt'),
        ),
        migrations.AddField(
            model_name='dpyfeetransaction',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
