# Generated by Django 2.0 on 2018-07-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_management', '0004_auto_20180702_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpyinstituteclassfee',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dpyinstituteclassfee',
            name='bifercations',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dpyinstituteclassfee',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
