# Generated by Django 2.0 on 2018-07-30 11:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fees_management', '0004_auto_20180728_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dpypaymentreceipt',
            old_name='institute_id',
            new_name='institute',
        ),
        migrations.AlterUniqueTogether(
            name='dpyuserfeeignore',
            unique_together={('status', 'institute_class_fee', 'user')},
        ),
    ]
