# Generated by Django 2.0 on 2018-07-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees_management', '0005_auto_20180703_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dpyinstituteclassfee',
            old_name='fee_type_id',
            new_name='fee_type',
        ),
        migrations.RenameField(
            model_name='dpyinstituteclassfee',
            old_name='institute_class_id',
            new_name='institute_class',
        ),
    ]
