# Generated by Django 2.0 on 2018-07-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees_management', '0006_auto_20180703_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dpyinstituteclassfee',
            old_name='bifercations',
            new_name='bifurcations',
        ),
    ]
