# Generated by Django 2.0 on 2018-07-31 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees_management', '0007_auto_20180730_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpypaymentreceipt',
            name='mop',
        ),
    ]
