# Generated by Django 2.0 on 2018-07-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_management', '0008_remove_dpypaymentreceipt_mop'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpypaymentreceipt',
            name='mop',
            field=models.IntegerField(null=True),
        ),
    ]
